src/__init__.py
from decouple import config
from flask import Flask
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)
app.config.from_object(config("APP_SETTINGS"))

bcrypt = Bcrypt(app)
db = SQLAlchemy(app)
migrate = Migrate(app, db)

login_manager = LoginManager() 
login_manager.init_app(app)
login_manager.login_view = "accounts.login"
login_manager.login_message_category = "danger"

from src.calculator.views import calculator_bp
from src.accounts.views import accounts_bp
from src.core.views import core_bp

app.register_blueprint(calculator_bp)
app.register_blueprint(accounts_bp)
app.register_blueprint(core_bp)

src/accounts/views.py
from src.utils import get_b64encoded_qr_image
from .forms import LoginForm, RegisterForm, TwoFactorForm
from src.accounts.models import User
from src import db, bcrypt
from flask_login import current_user, login_required, login_user, logout_user
from flask import Blueprint, flash, redirect, render_template, request, url_for
from src import login_manager

accounts_bp = Blueprint("accounts", __name__)

HOME_URL = "core.home"
LOGIN_URL = "accounts.login"
SETUP_2FA_URL = "accounts.setup_two_factor_auth"
VERIFY_2FA_URL = "accounts.verify_two_factor_auth"


@login_manager.user_loader
def load_user(user_id):
    return User.query.filter(User.id == int(user_id)).first()


#@accounts_bp.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        if current_user.is_two_factor_authentication_enabled:
            flash("Аккаунт уже зарегистрирован.", "info")
            return redirect(url_for(HOME_URL))
        else:
            flash(
                "Вы не включили двухфакторную аутентификацию. Пожалуйста, сначала включите ее для входа в систему.", "info")
            return redirect(url_for(SETUP_2FA_URL))
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        try:
            user = User(username=form.username.data, password=form.password.data)
            db.session.add(user)
            db.session.commit()

            login_user(user)
            flash("Вы зарегистрированы. Для входа в систему вам необходимо сначала включить двухфакторную аутентификацию.", "success")

            return redirect(url_for(SETUP_2FA_URL))
        except Exception:
            db.session.rollback()
            flash("Не удалось зарегистрироваться. Пожалуйста, попробуйте снова.", "danger")

    return render_template("accounts/register.html", form=form)


@accounts_bp.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        if current_user.is_two_factor_authentication_enabled and current_user.is_two_factor_authenticated:
            flash("Вы уже вошли в аккаунт.", "info")
            return redirect(url_for(HOME_URL))
        elif not current_user.is_two_factor_authentication_enabled:
            flash(
                "Вы не включили двухфакторную аутентификацию. Пожалуйста, сначала включите ее для входа в систему.", "info")
            return redirect(url_for(SETUP_2FA_URL))
        else: 
            flash("Вы не ввели OTP код. Пожалуйста, введите код.", "info")
            return redirect(url_for(VERIFY_2FA_URL))
        
    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, request.form["password"]):
            login_user(user)
            if not current_user.is_two_factor_authentication_enabled:
                flash(
                    "Вы не включили двухфакторную аутентификацию. Пожалуйста, сначала включите ее для входа в систему.", "info")
                return redirect(url_for(SETUP_2FA_URL))
            return redirect(url_for(VERIFY_2FA_URL))
        elif not user:
            flash("Вы не зарегистрированы. Пожалуйста, обратитесь к администратору", "danger")
        else:
            flash("Неверное имя пользователя или пароль.", "danger")
    return render_template("accounts/login.html", form=form)


@accounts_bp.route("/logout")
@login_required
def logout():
    try:
        current_user.is_two_factor_authenticated = False
        db.session.commit()
        logout_user()
        flash("Вы вышли из аккаунта.", "success")
    except Exception:
            db.session.rollback()
            flash("Не удалось выйти из аккаунта. Пожалуйста, попробуйте снова.", "danger")
    
    return redirect(url_for(LOGIN_URL))



@accounts_bp.route("/setup-2fa")
@login_required
def setup_two_factor_auth():
    secret = current_user.secret_token
    uri = current_user.get_authentication_setup_uri()
    base64_qr_image = get_b64encoded_qr_image(uri)
    return render_template("accounts/setup-2fa.html", secret=secret, qr_image=base64_qr_image)


@accounts_bp.route("/verify-2fa", methods=["GET", "POST"])
@login_required
def verify_two_factor_auth():
    form = TwoFactorForm(request.form)
    if form.validate_on_submit():
        if current_user.is_otp_valid(form.otp.data):
            try:
                if current_user.is_two_factor_authentication_enabled:
                    current_user.is_two_factor_authenticated = True
                    db.session.commit()
                    flash("Двухфакторная аутентификация прошла успешно. Вы вошли в аккаунт!", "success")
                    return redirect(url_for(HOME_URL))
                else:
                    current_user.is_two_factor_authenticated = True
                    current_user.is_two_factor_authentication_enabled = True
                    db.session.commit()
                    flash("Двухфакторная аутентификация прошла успешно. Вы вошли в систему!", "success")
                    return redirect(url_for(HOME_URL))
            except Exception:
                    db.session.rollback()
                    flash("Не удалось настроить двухфакторную аутентификацию. Пожалуйста, попробуйте снова.", "danger")
                    return redirect(url_for(VERIFY_2FA_URL))
        else:
            flash("Недействительный OTP. Пожалуйста, попробуйте снова.", "danger")
            return redirect(url_for(VERIFY_2FA_URL))
    else:
        if not current_user.is_two_factor_authentication_enabled:
            flash(
                "Вы не включили двухфакторную аутентификацию. Пожалуйста, сначала включите ее.", "info")
        return render_template("accounts/verify-2fa.html", form=form)

src/core/views.py
from flask_login import current_user, login_required, login_user, logout_user
from flask import (
    Blueprint,
    render_template,
    request,
    session,
    flash,
    send_file,
    redirect,
    url_for,
)
from fileinput import filename
from werkzeug.utils import secure_filename
from src import app, db
from src.calculator.models import Patient
from src.calculator.regression import Regression
from src.calculator.views import Data,groups_expected_val,regression
from datetime import datetime
from .forms import RegisterForm, AnaliticsForm
from src.accounts.models import User
import json
import plotly
import plotly.express as px
import plotly.graph_objects as go
import pandas as pd
import os
import csv
import pickle
import uuid
import json
from src.calculator.views import (
    calculate_age_at_operation,
    calculate_bmi,
    calculate_post_operation_duration,
    calculate_illness_duration,
)

core_bp = Blueprint("core", __name__)


def get_model(path):
    deserialize_array = None
    if len(path) == 0:
        path = "src/statistics/model.pkl"
    with open(path, "rb") as f:
        deserialize_array = pickle.load(f)
        data = Regression(deserialize_array)
    return data


Data = get_model("")
regression = Data.model
groups_expected_val = Data.groups_expected_val
cat_factor = {
    "gender": "Пол",
    "surgery_type": "Тип операции",
    "therapy_before_surgery": "Сахароснижающая терапия до операции",
    "arterial_hypertension_degree": "Степень артериальной гипертензии",
    "dyslipidemia": "Дислипидемия",
    "heredity": "Наследственность по ожирению и СД2",
    "complications_history": "Осложнения Сахарного диабета 2 типа в анамнезе",
    "gestational_diabetes": "Гестационный Сахарный Диабет в анамнезе",
}

nums_factor = {
    "X1_age_at_surgery": "Возраст на момент проведения операции",
    "X2_period_after_surgery": "Длительность периода после операции",
    "X3_max_BMI_before_surgery": "Максимальный ИМТ до операции",
    "X4_BMI_before_surgery": "ИМТ перед операцией",
    "X5_BMI_at_survey": "ИМТ на момент опроса",
    "X6_birth_weight": "Масса тела при рождении",
    "X7_min_BMI_after_surgery": "Минимальный ИМТ после операции",
    "X8_illness_duration": "Длительность СД2",
    "X9_HbA1c_before_surgery": "Уровень гликированного гемоглобина в крови до операции",
}
VERIFY_2FA_URL = "accounts.verify_two_factor_auth"


@core_bp.route("/home")
@login_required
def home():
    if current_user.is_two_factor_authenticated:
        plot = get_Y_plot()
        return render_template("core/index.html", graphJSON=plot)

    flash("Вы не ввели OTP код. Пожалуйста, введите код.", "info")
    return redirect(url_for(VERIFY_2FA_URL))


def get_Y_plot():
    column_data_pred = db.session.query(Patient.HbA1c_predicted).all()
    arr_pred = [record.HbA1c_predicted for record in column_data_pred]

    column_data_Y = db.session.query(Patient.Target_HbA1c_now).all()
    arr_Y = [record.Target_HbA1c_now for record in column_data_Y]

    dataframe = pd.DataFrame({"Предсказанный Y": arr_pred, "Y": arr_Y})
    dataframe["Предсказанный Y"] = dataframe["Предсказанный Y"].astype(float)
    dataframe["index"] = dataframe.index
    fig = px.line(
        dataframe, x="index", y="Предсказанный Y", markers=True, labels={'Предсказанный Y': "Предсказанный Y"}
    )
    fig.update_traces(line_color="#147852")
    fig_Y = px.line(dataframe, x="index", y="Y", markers=True,labels={'Y': "Y"})
    fig = go.Figure(data=fig.data + fig_Y.data)
    fig.update_layout(title="График предсказанного уровня HbA1c и нынешнего уровня HbA1c пациентов",showlegend=True)
    # fig.add_scatter(x=dataframe["index"], y=dataframe["Y"], mode='lines')
    graphJSON = json.dumps(fig, cls=plotly.utils.PlotlyJSONEncoder)

    return graphJSON


@core_bp.route("/admin", methods=["GET", "POST"])
@login_required
def admin_console():
    if current_user.is_two_factor_authenticated:
        data = db.session.query(User).all()
        form = RegisterForm(request.form)
        if form.validate_on_submit():
            try:
                user = User(username=form.username.data, password=form.password.data)
                db.session.add(user)
                db.session.commit()
                data = db.session.query(User).all()
            except Exception:
                db.session.rollback()
                flash("Регистрация не удалась. Пожалуйста, попробуйте снова.", "danger")
        return render_template(
            "core/administration.html",
            form=form,
            result=json.dumps(
                [record.serialize for record in data], ensure_ascii=False
            ),
        )

    flash("Вы не ввели OTP код. Пожалуйста, введите код.", "info")
    return redirect(url_for(VERIFY_2FA_URL))


@core_bp.route("/analitics", methods=["GET", "POST"])
@login_required
def get_analitics():
    if not current_user.is_two_factor_authenticated:
        flash("Вы не ввели OTP код. Пожалуйста, введите код.", "info")
        return redirect(url_for(VERIFY_2FA_URL))

    form = AnaliticsForm(request.form)
    if form.validate_on_submit():
        column = form.variable.data
        plot_div = draw_plot(column)
        return render_template("core/analitics.html", form=form, graphJSON=plot_div)
    else:
        return render_template("core/analitics.html", form=form)


def draw_plot(column):
    column_data = db.session.query(getattr(Patient, column)).all()
    arr = [getattr(record, column) for record in column_data]

    if column in cat_factor:
        dataframe = pd.DataFrame({cat_factor[column]: arr})
        dataframe[cat_factor[column]] = dataframe[cat_factor[column]].astype(str)
        value_counts = dataframe[cat_factor[column]].value_counts()

        df_value_counts = pd.DataFrame(value_counts)
        df_value_counts = df_value_counts.reset_index()
        df_value_counts.columns = [cat_factor[column], "Количество"]
        fig = px.bar(df_value_counts, x=cat_factor[column], y="Количество",title=f"График подсчета дискретного фактора {cat_factor[column]}")
        graphJSON = json.dumps(fig, cls=plotly.utils.PlotlyJSONEncoder)
    else:
        column_data_Y = db.session.query(Patient.Target_HbA1c_now).all()
        arr_Y = [record.Target_HbA1c_now for record in column_data_Y]
        dataframe = pd.DataFrame({nums_factor[column]: arr, "Y": arr_Y})
        dataframe[nums_factor[column]] = dataframe[nums_factor[column]].astype(float)
        fig = px.scatter(
            dataframe,
            x=nums_factor[column],
            y="Y",
            title=f"Диаграмма рассеяния для {nums_factor[column]} и Уровня HbA1c",
        )
        graphJSON = json.dumps(fig, cls=plotly.utils.PlotlyJSONEncoder)

    return graphJSON


@core_bp.route("/view_patients")
@login_required
def get_table():
    if current_user.is_two_factor_authenticated:
        data = db.session.query(Patient).all()
        return render_template(
            "core/view_patients.html",
            result=json.dumps(
                [record.serialize for record in data], ensure_ascii=False
            ),
        )

    flash("Вы не ввели OTP код. Пожалуйста, введите код.", "info")
    return redirect(url_for(VERIFY_2FA_URL))


@core_bp.route("/home", methods=["GET", "POST"])
@login_required
def uploadFile():
    if current_user.is_two_factor_authenticated:
        if request.method == "POST":
            count = 0
            try:
                f = request.files.get("file")
                data_filename = secure_filename(f.filename)

                if len(data_filename) == 0:
                    flash(f"Выберите файл загрузки!", "danger")
                    plot = get_Y_plot()
                    return render_template("core/index.html", graphJSON=plot)
                elif data_filename.find(".pkl"):
                    set_model(f,data_filename)
                    plot = get_Y_plot()
                    return render_template("core/index.html", graphJSON=plot)
                
                f.save(os.path.join(app.config["UPLOAD_FOLDER"], data_filename))
                session["uploaded_data_file_path"] = os.path.join(
                    app.config["UPLOAD_FOLDER"], data_filename
                )
                nums = None
                with open(session.get("uploaded_data_file_path", None), "r") as f:
                    nums = f.read().splitlines()

                check_arr = nums[0].split(",")
                if (
                    nums[0]
                    == "Дата опроса,ФИО,Дата рождения (дд.мм.ГГГГ),Пол,Рост (М),Масса тела при рождении (КГ),Масса тела на момент опроса (КГ),Дата выявления СД2,Тип операции,Дата операции (дд.мм.ГГГГ),Максимальная масса тела до операции(КГ),Масса тела перед операцией(КГ),Минимальная масса тела после операции(КГ),Сахароснижающая терапия до операции,Уровень гликированного гемоглобина в крови до операции (%),Степень Артериальной гипертензии,Дислипидемия,Наследственность по ожирению и Сахарному Диабету 2 типа,Осложнения Сахарного диабета 2 типа в анамнезе,Гестационный Сахарный Диабет в анамнезе,Уровень гликированного гемоглобина в крови на момент опроса (%)"
                ):
                    nums.pop(0)
                    for i in nums:
                        data = i.split(sep=",")
                        if db.session.query(Patient).filter(
                            Patient.survey_date
                            == datetime.strptime(data[0], "%d.%m.%Y"),
                            Patient.fullname == data[1],
                            Patient.birthdate == datetime.strptime(data[2], "%d.%m.%Y"),
                            Patient.gender == data[3],
                            Patient.X6_birth_weight == float(data[5]),
                            Patient.diagnosis_date
                            == datetime.strptime(data[7], "%d.%m.%Y"),
                            Patient.surgery_type == data[8],
                        ).count() != 0 or len(data) != len(check_arr):
                            break

src/templates/_base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Diabetes</title>
    <!-- meta -->
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <!-- styles -->
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static', filename="styles.css")}}">
    {% block css %}{% endblock %}
  </head>
  <body>

    {% include "navigation.html" %}

    <div class="container">

      <br>

      <!-- messages -->
      {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
      <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
          {% for category, message in messages %}
          <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
           {{message}}
           <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
          {% endfor %}
        </div>
        <div class="col-md-4"></div>
      </div>
      {% endif %}
      {% endwith %}

      <!-- child template -->
      {% block content %}{% endblock %}

    </div>

    <!-- scripts -->
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    <script>
      function openNav() {
        document.getElementById("mySidebar").style.width = "250px"; // Задаем ширину sidebar
      }

      function closeNav() {
        document.getElementById("mySidebar").style.width = "0"; // Скрываем sidebar
      }

    </script>
    {% block js %}{% endblock %}
  </body>
</html>

src/templates/navigation.html
<!-- Navigation -->
<nav class="navbar bg-dark navbar-expand-lg bg-body-tertiary p-3" data-bs-theme="dark">
  <div class="container-fluid">
      <!-- Поместите кнопку открытия меню в начало навбара -->
      {% if current_user.is_authenticated and current_user.is_two_factor_authenticated %}
      <button class="openbtn" onclick="openNav()">☰</button>
      {% endif %}
      <!-- Ссылка на главную или заголовок сайта -->
      <a class="navbar-brand" href="/">
          Прогнозирование риска рецидива сахарного диабета 2 типа после достижения ремиссии в ходе бариатрической хирургии
      </a>

      <!-- Кнопка для мобильных устройств -->
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Содержимое навбара -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
          {% if current_user.is_authenticated and current_user.is_two_factor_authenticated %}
          <a href="{{ url_for('accounts.logout') }}"><button type="button" class="btn btn-danger me-2">Выйти</button></a>
          {% else %}
          <a href="{{ url_for('accounts.login') }}"><button type="button" class="btn btn-outline-primary me-2">Войти</button></a>
          {% endif %}
      </div>
  </div>

  <!-- Sidebar -->
  {% if current_user.is_authenticated and current_user.is_two_factor_authenticated %}
  <div id="mySidebar" class="sidebar">
      <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">×</a>
      <a href="{{ url_for('core.home') }}">Главная</a>
      <a href="{{ url_for('core.get_table') }}">Пациенты</a>
      <a href="{{ url_for('core.get_analitics') }}">Аналитика</a>
      <a href="{{ url_for('core.admin_console') }}">Пользователи</a>
  </div>
  {% endif %}
</nav>