src/accounts/models.py
from datetime import datetime

import pyotp
from flask_login import UserMixin

from src import bcrypt, db
from config import Config


class User(UserMixin, db.Model):

    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String, unique=True, nullable=False)
    password = db.Column(db.String, nullable=False)
    created_at = db.Column(db.DateTime, nullable=False)
    is_two_factor_authentication_enabled = db.Column(
        db.Boolean, nullable=False, default=False)
    is_two_factor_authenticated= db.Column(
        db.Boolean, nullable=False, default=False)
    secret_token = db.Column(db.String, unique=True)

    def __init__(self, username, password):
        self.username = username
        self.password = bcrypt.generate_password_hash(password)
        self.created_at = datetime.now()
        self.secret_token = pyotp.random_base32()

    def get_authentication_setup_uri(self):
        return pyotp.totp.TOTP(self.secret_token).provisioning_uri(
            name=self.username, issuer_name=Config.APP_NAME)

    def is_otp_valid(self, user_otp):
        totp = pyotp.parse_uri(self.get_authentication_setup_uri())
        return totp.verify(user_otp)
    
    @property
    def serialize(self):
        return {
            "ID": self.id,
            "username": self.username,
            "created_date": self.created_at.strftime("%d.%m.%Y"),
            "2FA_enabled": self.is_two_factor_authentication_enabled
        }
    
    def __repr__(self):
        return f"<user {self.username}>"

src/accounts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField
from wtforms.validators import DataRequired, EqualTo, Length, InputRequired

from src.accounts.models import User


class RegisterForm(FlaskForm):
    username = StringField(
        "Username", validators=[DataRequired(), Length(min=6, max=40)]
    )
    password = PasswordField(
        "Password", validators=[DataRequired(), Length(min=6, max=25)]
    )
    confirm = PasswordField(
        "Repeat password",
        validators=[
            DataRequired(),
            EqualTo("password", message="Пароли не совпадают."),
        ],
    )

    def validate(self, extra_validators):
        initial_validation = super(RegisterForm, self).validate(extra_validators)
        if not initial_validation:
            return False
        user = User.query.filter_by(username=self.username.data).first()
        if user:
            self.username.errors.append("Пользователь уже зарегистрирован.")
            return False
        if self.password.data != self.confirm.data:
            self.password.errors.append("Пароли не совпадают.")
            return False
        return True


class LoginForm(FlaskForm):
    username = StringField("Username", validators=[DataRequired()])
    password = PasswordField("Password", validators=[DataRequired()])


class TwoFactorForm(FlaskForm):
    otp = StringField('Enter OTP', validators=[
                      InputRequired(), Length(min=6, max=6)])

src/__init__.py
from decouple import config
from flask import Flask
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)
app.config.from_object(config("APP_SETTINGS"))

bcrypt = Bcrypt(app)
db = SQLAlchemy(app)
migrate = Migrate(app, db)

login_manager = LoginManager() 
login_manager.init_app(app)
login_manager.login_view = "accounts.login"
login_manager.login_message_category = "danger"

from src.calculator.views import calculator_bp
from src.accounts.views import accounts_bp
from src.core.views import core_bp

app.register_blueprint(calculator_bp)
app.register_blueprint(accounts_bp)
app.register_blueprint(core_bp)

src/accounts/views.py
from src.utils import get_b64encoded_qr_image
from .forms import LoginForm, RegisterForm, TwoFactorForm
from src.accounts.models import User
from src import db, bcrypt
from flask_login import current_user, login_required, login_user, logout_user
from flask import Blueprint, flash, redirect, render_template, request, url_for
from src import login_manager

accounts_bp = Blueprint("accounts", __name__)

HOME_URL = "core.home"
LOGIN_URL = "accounts.login"
SETUP_2FA_URL = "accounts.setup_two_factor_auth"
VERIFY_2FA_URL = "accounts.verify_two_factor_auth"


@login_manager.user_loader
def load_user(user_id):
    return User.query.filter(User.id == int(user_id)).first()


#@accounts_bp.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        if current_user.is_two_factor_authentication_enabled:
            flash("Аккаунт уже зарегистрирован.", "info")
            return redirect(url_for(HOME_URL))
        else:
            flash(
                "Вы не включили двухфакторную аутентификацию. Пожалуйста, сначала включите ее для входа в систему.", "info")
            return redirect(url_for(SETUP_2FA_URL))
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        try:
            user = User(username=form.username.data, password=form.password.data)
            db.session.add(user)
            db.session.commit()

            login_user(user)
            flash("Вы зарегистрированы. Для входа в систему вам необходимо сначала включить двухфакторную аутентификацию.", "success")

            return redirect(url_for(SETUP_2FA_URL))
        except Exception:
            db.session.rollback()
            flash("Не удалось зарегистрироваться. Пожалуйста, попробуйте снова.", "danger")

    return render_template("accounts/register.html", form=form)


@accounts_bp.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        if current_user.is_two_factor_authentication_enabled and current_user.is_two_factor_authenticated:
            flash("Вы уже вошли в аккаунт.", "info")
            return redirect(url_for(HOME_URL))
        elif not current_user.is_two_factor_authentication_enabled:
            flash(
                "Вы не включили двухфакторную аутентификацию. Пожалуйста, сначала включите ее для входа в систему.", "info")
            return redirect(url_for(SETUP_2FA_URL))
        else: 
            flash("Вы не ввели OTP код. Пожалуйста, введите код.", "info")
            return redirect(url_for(VERIFY_2FA_URL))
        
    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, request.form["password"]):
            login_user(user)
            if not current_user.is_two_factor_authentication_enabled:
                flash(
                    "Вы не включили двухфакторную аутентификацию. Пожалуйста, сначала включите ее для входа в систему.", "info")
                return redirect(url_for(SETUP_2FA_URL))
            return redirect(url_for(VERIFY_2FA_URL))
        elif not user:
            flash("Вы не зарегистрированы. Пожалуйста, обратитесь к администратору", "danger")
        else:
            flash("Неверное имя пользователя или пароль.", "danger")
    return render_template("accounts/login.html", form=form)


@accounts_bp.route("/logout")
@login_required
def logout():
    try:
        current_user.is_two_factor_authenticated = False
        db.session.commit()
        logout_user()
        flash("Вы вышли из аккаунта.", "success")
    except Exception:
            db.session.rollback()
            flash("Не удалось выйти из аккаунта. Пожалуйста, попробуйте снова.", "danger")
    
    return redirect(url_for(LOGIN_URL))



@accounts_bp.route("/setup-2fa")
@login_required
def setup_two_factor_auth():
    secret = current_user.secret_token
    uri = current_user.get_authentication_setup_uri()
    base64_qr_image = get_b64encoded_qr_image(uri)
    return render_template("accounts/setup-2fa.html", secret=secret, qr_image=base64_qr_image)


@accounts_bp.route("/verify-2fa", methods=["GET", "POST"])
@login_required
def verify_two_factor_auth():
    form = TwoFactorForm(request.form)
    if form.validate_on_submit():
        if current_user.is_otp_valid(form.otp.data):
            try:
                if current_user.is_two_factor_authentication_enabled:
                    current_user.is_two_factor_authenticated = True
                    db.session.commit()
                    flash("Двухфакторная аутентификация прошла успешно. Вы вошли в аккаунт!", "success")
                    return redirect(url_for(HOME_URL))
                else:
                    current_user.is_two_factor_authenticated = True
                    current_user.is_two_factor_authentication_enabled = True
                    db.session.commit()
                    flash("Двухфакторная аутентификация прошла успешно. Вы вошли в систему!", "success")
                    return redirect(url_for(HOME_URL))
            except Exception:
                    db.session.rollback()
                    flash("Не удалось настроить двухфакторную аутентификацию. Пожалуйста, попробуйте снова.", "danger")
                    return redirect(url_for(VERIFY_2FA_URL))
        else:
            flash("Недействительный OTP. Пожалуйста, попробуйте снова.", "danger")
            return redirect(url_for(VERIFY_2FA_URL))
    else:
        if not current_user.is_two_factor_authentication_enabled:
            flash(
                "Вы не включили двухфакторную аутентификацию. Пожалуйста, сначала включите ее.", "info")
        return render_template("accounts/verify-2fa.html", form=form)

src/calculator/views.py
from .forms import CalculateForm
from src.calculator.models import Patient
from src import db
from datetime import datetime
from flask import Blueprint, flash, redirect, render_template, request, url_for
from src.calculator.regression import Regression
import pickle
import pandas as pd
import uuid

calculator_bp = Blueprint("calculator", __name__)

def get_model():
    deserialize_array = None
    with open("src/statistics/model.pkl", "rb") as f:
        deserialize_array = pickle.load(f)
        data = Regression(deserialize_array)
    return data

def set_model(path):
    deserialize_array = None
    with open(path, "rb") as f:
        deserialize_array = pickle.load(f)
        data = Regression(deserialize_array)

global Data
global regression
global groups_expected_val

Data = get_model()
regression = Data.model
groups_expected_val = Data.groups_expected_val


def calculate_age_at_operation(birthdate, operation_date):
    return (operation_date - birthdate).days / 365


def calculate_post_operation_duration(survey_date, operation_date):
    return (survey_date - operation_date).days / 365


def calculate_bmi(weight, height):
    height = float(height)
    weight = float(weight)
    return weight / (height**2)


def calculate_illness_duration(operation_date, diagnosis_date):
    return (operation_date - diagnosis_date).days / 365


@calculator_bp.route("/", methods=["GET", "POST"])
def calculate():
    form = CalculateForm(request.form)
    result = 0
    if form.validate_on_submit():
        try:
            if (
                db.session.query(Patient)
                .filter(
                    Patient.survey_date
                    == form.survey_date.data.strftime("%Y-%m-%d %H:%M:%S.%f"),
                    Patient.fullname == form.fullname.data,
                    Patient.birthdate
                    == form.birthdate.data.strftime("%Y-%m-%d %H:%M:%S.%f"),
                    Patient.gender == form.gender.data,
                    Patient.X6_birth_weight == form.X6_birth_weight.data,
                    Patient.diagnosis_date
                    == form.diagnosis_date.data.strftime("%Y-%m-%d %H:%M:%S.%f"),
                    Patient.surgery_type == form.surgery_type.data,
                )
                .count()
                != 0
            ):
                flash(f"Пациент с введенной датой опроса существует!", "danger")
                return render_template("calculator/survey.html", form=form, properties={})

            get_pat_uuid = str(uuid.uuid4())
            patient = Patient(
                pat_uuid=get_pat_uuid,
                survey_date=form.survey_date.data,
                fullname=form.fullname.data,
                birthdate=form.birthdate.data,
                gender=form.gender.data,
                height=form.height.data,
                X6_birth_weight=form.X6_birth_weight.data,
                weight=form.weight.data,
                diagnosis_date=form.diagnosis_date.data,
                surgery_type=form.surgery_type.data,
                surgery_date=form.surgery_date.data,
                max_weight_before_surgery=form.max_weight_before_surgery.data,
                weight_before_surgery=form.weight_before_surgery.data,
                min_weight_after_surgery=form.min_weight_after_surgery.data,
                therapy_before_surgery=form.therapy_before_surgery.data,
                X9_HbA1c_before_surgery=form.X9_HbA1c_before_surgery.data,
                arterial_hypertension_degree=form.arterial_hypertension_degree.data,
                dyslipidemia=form.dyslipidemia.data,
                heredity=form.heredity.data,
                complications_history=form.complications_history.data,
                gestational_diabetes=form.gestational_diabetes.data,
                X1_age_at_surgery=calculate_age_at_operation(
                    form.birthdate.data, form.surgery_date.data
                ),
                X2_period_after_surgery=calculate_post_operation_duration(
                    form.survey_date.data, form.surgery_date.data
                ),
                X3_max_BMI_before_surgery=calculate_bmi(
                    form.max_weight_before_surgery.data, form.height.data
                ),
                X4_BMI_before_surgery=calculate_bmi(
                    form.weight_before_surgery.data, form.height.data
                ),
                X5_BMI_at_survey=calculate_bmi(form.weight.data, form.height.data),
                X7_min_BMI_after_surgery=calculate_bmi(
                    form.min_weight_after_surgery.data, form.height.data
                ),
                X8_illness_duration=calculate_illness_duration(
                    form.surgery_date.data, form.diagnosis_date.data
                ),
                Target_HbA1c_now=form.Target_HbA1c_now.data,
            )

            group = ";".join(
                [patient.gender, patient.surgery_type, patient.therapy_before_surgery]
            )
            X = pd.DataFrame(
                {
                    "X1": [patient.X1_age_at_surgery],
                    "X2": [patient.X2_period_after_surgery],
                    "X3": [patient.X3_max_BMI_before_surgery],
                    "X4": [patient.X4_BMI_before_surgery],
                    "X5": [patient.X5_BMI_at_survey],
                    "X6": [float(patient.X6_birth_weight * 1000)],
                    "X7": [patient.X7_min_BMI_after_surgery],
                    "X8": [patient.X8_illness_duration],
                    "X9": [float(patient.X9_HbA1c_before_surgery / 100)],
                    "const": [1],
                }
            )

            if group in groups_expected_val:
                result_reg = regression.predict(X) + groups_expected_val[group][0]
            else:
                result_reg = regression.predict(X) + groups_expected_val["M_data"]

            patient.HbA1c_predicted = result_reg * 100
            properties = get_properties(
                [
                    patient.X1_age_at_surgery,
                    patient.X2_period_after_surgery,
                    patient.X3_max_BMI_before_surgery,
                    patient.X4_BMI_before_surgery,
                    patient.X5_BMI_at_survey,
                    patient.X7_min_BMI_after_surgery,
                    patient.X8_illness_duration,
                ]
            )
            db.session.add(patient)
            db.session.commit()

            result = float(result_reg * 100)
            message = get_result_message(result)
            result = format(result, ".2f")
            return render_template(
                "calculator/survey.html",
                form=form,
                result=result,
                message=message,
                properties=properties,
            )
        except Exception as e:
            db.session.rollback()
            flash(f"Непредвиденная ошибка при сохранении данных: {e}", "danger")
    else:
        for fieldName, errorMessages in form.errors.items():
            for err in errorMessages:
                flash(f"Ошибка в поле '{fieldName}': {err}", "danger")

    return render_template("calculator/survey.html", form=form, properties={})


def get_result_message(result):
    message = [
        "Риск возникновения Сахарного диабета 2 типа выше пограничного значения. Требуется медицинское обследование.",
        "Состояние здоровья находится в норме. Риск возникновения Сахарного диабета 2 типа ниже пограничного значения. Медицинская консультация не требуется.",
    ]
    if result >= 6.5:
        return message[0]
    else:
        return message[1]


def get_properties(properties):
    dictionary = [
        "Возраст на момент проведения операции",
        "Длительность периода после операции",
        "Максимальный индекс массы тела до операции",
        "Индекс массы тела перед операцией",
        "Индекс массы тела на момент опроса",
        "Минимальный индекс массы тела после операции",
        "Длительность сахарного диабета 2 типа",
    ]
    for ind in range(len(properties)):
        properties[ind] = format(properties[ind], ".2f")
    return dict(zip(dictionary, properties))

src/templates/core/administration.html
<!DOCTYPE html>
<html>
<head>
    <link href="https://unpkg.com/tabulator-tables/dist/css/tabulator.min.css" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static', filename="user_table.css")}}">
</head>
<body>

<!-- Navigation -->
<nav class="navbar bg-dark navbar-expand-lg bg-body-tertiary p-3" data-bs-theme="dark">
    <div class="container-fluid">
        <!-- Поместите кнопку открытия меню в начало навбара -->
        {% if current_user.is_authenticated and current_user.is_two_factor_authenticated  %}
        <button class="openbtn" onclick="openNav()">☰</button>
        {% endif %}
        <!-- Ссылка на главную или заголовок сайта -->
        <a class="navbar-brand" href="/">
            Прогнозирование риска рецидива сахарного диабета 2 типа после достижения ремиссии в ходе бариатрической хирургии
        </a>

        <!-- Кнопка для мобильных устройств -->
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Содержимое навбара -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            {% if current_user.is_authenticated and current_user.is_two_factor_authenticated %}
            <a href="{{ url_for('accounts.logout') }}"><button type="button" class="btn btn-danger me-2">Выйти</button></a>
            {% else %}
            <a href="{{ url_for('accounts.login') }}"><button type="button" class="btn btn-outline-primary me-2">Войти</button></a>
            {% endif %}
        </div>
    </div>

    <!-- Sidebar -->
    <div id="mySidebar" class="sidebar">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">×</a>
        <a href="{{ url_for('core.home') }}">Главная</a>
        <a href="{{ url_for('calculator.calculate') }}">Калькулятор</a>
        <a href="{{ url_for('core.get_table') }}">Пациенты</a>
        <a href="{{ url_for('core.get_analitics') }}">Аналитика</a>
        <a href="{{ url_for('core.admin_console') }}">Пользователи</a>
    </div>
</nav>


  <head>
    <title>Форма регистрации</title>
    <style>
      .overlay {
        display: none;
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-color: rgba(0, 0, 0, 0.5);
        z-index: 1000;
      }

      .form-container {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        background-color: white;
        padding: 20px;
        border-radius: 5px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
      }

      .btn-success {
        background-color: #0d6efd;
      }
      .btn:hover {
        background-color: #0d6efd;
      }
      .container-suc-but-over{
        display: flex;
        justify-content: flex-end;
      }
    </style>
  </head>

  <body>
    <div class="container-suc-but-over">
      <button class="btn btn-success btn-blok" id="show-form-btn" type="button">Новый пользователь</button>
    </div>
    <div class="overlay" id="overlay">
      <div class="form-container">
        <span class="close-button" onclick="closeForm()">✖️</span>
        <form role="form" method="post" action="">
          {{ form.csrf_token }}
          <h1 class="h3 mb-3 fw-normal text-center">Создание пользователя</h1>

          <div class="form-floating">
            {{ form.username(placeholder="username", class="form-control mb-2") }}
            {{ form.username.label }}
            {% if form.username.errors %}
            {% for error in form.username.errors %}
            <div class="alert alert-danger" role="alert">
              {{ error }}
            </div>
            {% endfor %}
            {% endif %}
          </div>
          <div class="form-floating">
            {{ form.password(placeholder="password", class="form-control mb-2") }}
            {{ form.password.label }}
            {% if form.password.errors %}
            {% for error in form.password.errors %}
            <div class="alert alert-danger" role="alert">
              {{ error }}
            </div>
            {% endfor %}
            {% endif %}
          </div>
          <div class="form-floating">
            {{ form.confirm(placeholder="Confirm Password", class="form-control mb-2") }}
            {{ form.confirm.label }}
            {% if form.confirm.errors %}
            {% for error in form.confirm.errors %}
            <div class="alert alert-danger" role="alert">
              {{ error }}
            </div>
            {% endfor %}
            {% endif %}
          </div>
          <button class="w-100 btn btn-lg btn-primary" type="submit">Создать</button>
        </form>
      </div>
    </div>

    <script>
      const showFormBtn = document.getElementById('show-form-btn');
      const overlay = document.getElementById('overlay');
      function closeForm() {
        document.getElementById('overlay').style.display = 'none';
      }
      showFormBtn.addEventListener('click', () => {
        overlay.style.display = 'block';
      });
    </script>
  </body>

  <div id="table"></div>

  <script src="https://unpkg.com/tabulator-tables/dist/js/tabulator.min.js"></script>
  <script type="text/javascript" src="https://oss.sheetjs.com/sheetjs/xlsx.full.min.js"></script>
  <script src='https://cdnjs.cloudflare.com/ajax/libs/luxon/3.3.0/luxon.min.js'></script>
  <link href="/dist/css/tabulator_bootstrap5.min.css" rel="table-striped">
  <script>

    document.addEventListener("DOMContentLoaded", function () {
      var data = {{ result| tojson
    }};
    var table = new Tabulator("#table", {
      data: data,
      layout: "fitColumns",
      printAsHtml: true,
      printStyled: true,
      printRowRange: "all",
      columns: [
        { title: "ID", field: "ID", sorter: "number", headerFilter: "input", headerFilterPlaceholder: "Поиск по ID" },
        { title: "Логин", field: "username", sorter: "string", headerFilter: "input", headerFilterPlaceholder: "Поиск по Логину" },
        { title: "Дата регистрации", field: "created_date", formatter: "datetime", formatterParams: { inputFormat: "dd.MM.yyyy", outputFormat: "dd-MM-yyyy" }, sorter: "date", sorterParams: { format: "dd.MM.yyyy", alignEmptyValues: "top" }, headerFilter: "input", headerFilterPlaceholder: "Поиск по Дате регистрации" },
        { title: "Двухфакторная аутентификация", field: "2FA_enabled", sorter: "number", formatter: "tickCross", headerFilter: "input", headerFilterPlaceholder: "Поиск" },
      ],
      pagination: "local",
      paginationSize: 13,
      movableColumns: true,
      resizableRows: true
    });

    // Добавляем кнопку для скачивания
    var buttonsContainer = document.createElement("div");
    buttonsContainer.style.display = "flex";
    buttonsContainer.style.justifyContent = "flex-end"
    buttonsContainer.style.alignItems = "center";
    buttonsContainer.style.gap = "10px";

    var downloadButton = document.createElement("button-csv");
    downloadButton.textContent = "Скачать CSV";
    downloadButton.addEventListener('click', function () {
      table.download("csv", "users.csv");
    });

    var downloadButton2 = document.createElement("button-csv");
    downloadButton2.textContent = "Скачать XLSX";
    downloadButton2.addEventListener('click', function () {
      table.download("xlsx", "users.xlsx", { sheetName: "MyData" });
    });

    var downloadButton3 = document.createElement("button-csv");
    downloadButton3.textContent = "Распечатать страницу";
    downloadButton3.addEventListener('click', function () {
      table.print();
    });

    document.body.appendChild(downloadButton);
    document.body.appendChild(downloadButton2);
    document.body.appendChild(downloadButton3);

    buttonsContainer.appendChild(downloadButton);
    buttonsContainer.appendChild(downloadButton2);
    buttonsContainer.appendChild(downloadButton3);

    document.body.appendChild(buttonsContainer);


});


    function openNav() {
      document.getElementById("mySidebar").style.width = "250px"; // Задаем ширину sidebar
    }

    function closeNav() {
      document.getElementById("mySidebar").style.width = "0"; // Скрываем sidebar
    }


  </script>

</html>

src/templates/core/analitics.html
<!DOCTYPE html>
<html>

<head>
    <link href="https://unpkg.com/tabulator-tables/dist/css/tabulator.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{{url_for('static', filename='analitics.css')}}">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="https://d3js.org/d3.v7.min.js"></script>
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
</head>

<body>

    <!-- Navigation -->
    <nav class="navbar bg-dark navbar-expand-lg bg-body-tertiary p-3" data-bs-theme="dark">
        <div class="container-fluid">
            <!-- Поместите кнопку открытия меню в начало навбара -->
            {% if current_user.is_authenticated and current_user.is_two_factor_authenticated %}
            <button class="openbtn" onclick="openNav()">☰</button>
            {% endif %}
            <!-- Ссылка на главную или заголовок сайта -->
            <a class="navbar-brand" href="/">
                Прогнозирование риска рецидива сахарного диабета 2 типа после достижения ремиссии в ходе бариатрической
                хирургии
            </a>

            <!-- Кнопка для мобильных устройств -->
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <!-- Содержимое навбара -->
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                {% if current_user.is_authenticated and current_user.is_two_factor_authenticated %}
                <a href="{{ url_for('accounts.logout') }}"><button type="button"
                        class="btn btn-danger me-2">Выйти</button></a>
                {% else %}
                <a href="{{ url_for('accounts.login') }}"><button type="button"
                        class="btn btn-outline-primary me-2">Войти</button></a>
                {% endif %}
            </div>
        </div>

        <!-- Sidebar -->
        <div id="mySidebar" class="sidebar">
            <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">×</a>
            <a href="{{ url_for('core.home') }}">Главная</a>
            <a href="{{ url_for('calculator.calculate') }}">Калькулятор</a>
            <a href="{{ url_for('core.get_table') }}">Пациенты</a>
            <a href="{{ url_for('core.get_analitics') }}">Аналитика</a>
            <a href="{{ url_for('core.admin_console') }}">Пользователи</a>
        </div>
    </nav>
    <div class="analize-container">
        <div class="chart-container">
            <div id='chart' class='chart'></div>
        </div>
        <div class="filter-container">
            <form method="POST">
                <p>{{ form.variable.label }} {{ form.variable }}</p>
                {% if form.variable.errors %}
                {% for error in form.variable.errors %}
                <div class="alert alert-danger" role="alert">{{ error }}</div>
                {% endfor %}
                {% endif %}
                <p><input type="submit" value="Отрисовать"></p>
            </form>
        </div>
    </div>

    <script src='https://cdn.plot.ly/plotly-latest.min.js'></script>
    <script type='text/javascript'>
        var graphs = {{ graphJSON | safe}};
        Plotly.plot('chart', graphs, {});
    </script>
    <script src="https://unpkg.com/tabulator-tables/dist/js/tabulator.min.js"></script>
    <script>
        function openNav() {
            document.getElementById("mySidebar").style.width = "250px";
        }

        function closeNav() {
            document.getElementById("mySidebar").style.width = "0";
        }

    </script>
</body>

</html>